# Generated by Django 4.1.6 on 2023-02-08 13:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('cover', models.ImageField(null=True, upload_to='covers', verbose_name='Cover')),
                ('category', models.CharField(choices=[('1', 'Kita'), ('2', 'Auskarai'), ('3', 'Apyrankė'), ('4', 'Segė'), ('5', 'Kaklo papuošalas'), ('6', 'Aksesuaras'), ('7', 'Dovanų kuponas')], default='1', max_length=2)),
            ],
        ),
    ]
