# Generated by Django 4.1.6 on 2023-03-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_customer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Other'), ('2', 'Earrings'), ('3', 'Bracelet'), ('4', 'Brooch'), ('5', 'Necklece'), ('6', 'Accessories'), ('7', 'Gift Card'), ('8', 'Christmas wreath')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
