# Generated by Django 4.1.6 on 2023-03-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_shippingaddress_state_customer_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='telephone',
            field=models.CharField(max_length=20, null=True, verbose_name='Telephone number'),
        ),
    ]
