# Generated by Django 4.1.6 on 2023-03-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shippingaddress_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='Country'),
        ),
    ]
