# Generated by Django 4.1.6 on 2023-03-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shippingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
