# Generated by Django 4.1.6 on 2023-03-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Approved'), ('c', 'Cancelled'), ('d', 'Completed')], default='p', help_text='Status', max_length=1),
        ),
    ]
