# Generated by Django 4.1.6 on 2023-02-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzduotis',
            options={'verbose_name': 'Užduotis', 'verbose_name_plural': 'Užduotys'},
        ),
    ]
