# Generated by Django 4.1.6 on 2023-02-06 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_alter_uzduotis_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzduotis',
            name='vartotojas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
